library(eha)
library(tm)
library(Biograph)
library(lubridate)
library(qdap)
library(COUNT)
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(stringr)
library(forecast)
library(caret)
library(BTYD)
library(msm)
library(mvna)
library(survival)
library(muhaz)
library(tsintermittent)
library(TSclust)
library(hflights)
library(useful)
library(NbClust)
library(GGally)
library(mixAK)
library(bayesm)


colnames(CDNOW) <- c("Client", "Date", "NoPurchased", "Spent")
